server:
  port: ${APP_TIMS_PORT:5000}
  shutdown: immediate

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${TIMS_DB_HOST:localhost}:${TIMS_DB_PORT:1435};databaseName=${TIMS_DB_NAME:fotrn};encrypt=true;trustServerCertificate=true;
    username: ${TIMS_DB_USERNAME:sa}
    password: ${TIMS_DB_PASSOWRD:test@2022}

tims:
  base_url: ${TIMS_BASE_URL:http://197.248.125.81:8086/api/v3/}
  invoice_url: ${TIMS_INVOICE_URL:invoices}
  app_key: ${ACTIVATION_KEY:OzOs7YM816dR1knGxQs9iiUCVRJr/jblhC6ClPmRkQ8dLnGoBHFSn1spGYg8PNCj6HIiNz2BBn/X2Z0mopTkrFlJVtU7whx2goyhavr04a9gvbhNHZtpz0TAo53CsA50E9lwhAufp3Pw+zSEDPa9KEc/Wn0SPCQBCTjrcv6GDYc=}

#logging----------------------------------------------------------
logging:
  pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} | %-20.20thread | %5p | %-25.25logger{25}: %m%n'
  level:
    root: INFO
    com:
      tims: DEBUG
  file:
    name: ${LOG_PATH:/home/TIMS_LOGS/}${LOGFILE:today.log}
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH:/home/TIMS_LOGS/}%d{ddMMyyyy}.%i.log
      max-history: 500